spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guitteum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: http://localhost:9200

  jpa:
    show-sql: true

qdrant:
  host: localhost
  port: 6334

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG
    org.springframework.data.elasticsearch: DEBUG
